operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
hooks:
  pre-app-run: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  pre-app-build: node node_modules/@adobe/uix-guest/scripts/generate-metadata.js
  post-app-deploy: ./hooks/post-deploy.js
runtimeManifest:
  packages:
    ue-fdm-extension:
      license: Apache-2.0
      actions:
        fetchFDMTree:
          function: actions/fetchFDMTree/index.js
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            final: true
